/**
 * Infected foliage identifiers. Generated by tools/generateInfectedFoliagePack.js.
 * Do not edit by hand.
 */

export const FOLIAGE_SPECIES = [
    {
        "id": "short_grass",
        "title": "Grass",
        "vanilla": [
            "minecraft:short_grass",
            "minecraft:grass"
        ],
        "kind": "cross",
        "sound": "grass",
        "walkable": true,
        "worldgenWeight": 12
    },
    {
        "id": "tall_grass",
        "title": "Tall Grass",
        "vanilla": [
            "minecraft:tall_grass"
        ],
        "aliases": [
            "minecraft:double_tall_grass",
            "minecraft:tallgrass"
        ],
        "kind": "cross",
        "sound": "grass",
        "walkable": true,
        "tall": true,
        "worldgenWeight": 4
    },
    {
        "id": "fern",
        "title": "Fern",
        "vanilla": [
            "minecraft:fern"
        ],
        "kind": "cross",
        "sound": "grass",
        "walkable": true,
        "worldgenWeight": 4
    },
    {
        "id": "large_fern",
        "title": "Large Fern",
        "vanilla": [
            "minecraft:large_fern"
        ],
        "kind": "cross",
        "sound": "grass",
        "walkable": true,
        "tall": true,
        "worldgenWeight": 2
    },
    {
        "id": "firefly_bush",
        "title": "Firefly Bush",
        "vanilla": [
            "minecraft:firefly_bush"
        ],
        "kind": "cross",
        "sound": "grass",
        "walkable": true,
        "worldgenWeight": 0,
        "light": 4
    },
    {
        "id": "brown_mushroom",
        "title": "Brown Mushroom",
        "vanilla": [
            "minecraft:brown_mushroom"
        ],
        "kind": "cross",
        "sound": "grass",
        "walkable": true,
        "worldgenWeight": 2
    },
    {
        "id": "red_mushroom",
        "title": "Red Mushroom",
        "vanilla": [
            "minecraft:red_mushroom"
        ],
        "kind": "cross",
        "sound": "grass",
        "walkable": true,
        "worldgenWeight": 1
    },
    {
        "id": "red_shrub",
        "title": "Red Shrub",
        "vanilla": [
            "minecraft:red_shrub"
        ],
        "kind": "cross",
        "sound": "grass",
        "walkable": true,
        "worldgenWeight": 1
    },
    {
        "id": "leaf_litter",
        "title": "Leaf Litter",
        "vanilla": [
            "minecraft:leaf_litter"
        ],
        "kind": "litter",
        "sound": "grass",
        "walkable": true,
        "worldgenWeight": 3
    },
    {
        "id": "vine",
        "title": "Vines",
        "vanilla": [
            "minecraft:vine"
        ],
        "kind": "vine",
        "sound": "grass",
        "walkable": true,
        "worldgenWeight": 0
    },
    {
        "id": "brown_mushroom_block",
        "title": "Brown Mushroom Block",
        "vanilla": [
            "minecraft:brown_mushroom_block"
        ],
        "kind": "cube",
        "sound": "wood",
        "walkable": false,
        "worldgenWeight": 0
    },
    {
        "id": "red_mushroom_block",
        "title": "Red Mushroom Block",
        "vanilla": [
            "minecraft:red_mushroom_block"
        ],
        "kind": "cube",
        "sound": "wood",
        "walkable": false,
        "worldgenWeight": 0
    },
    {
        "id": "mushroom_stem",
        "title": "Mushroom Stem",
        "vanilla": [
            "minecraft:mushroom_stem"
        ],
        "kind": "cube",
        "sound": "wood",
        "walkable": false,
        "worldgenWeight": 0
    },
    {
        "id": "warped_roots",
        "title": "Warped Roots",
        "vanilla": [
            "minecraft:warped_roots"
        ],
        "kind": "cross",
        "sound": "grass",
        "walkable": true,
        "nether": true,
        "worldgenWeight": 0
    },
    {
        "id": "crimson_roots",
        "title": "Crimson Roots",
        "vanilla": [
            "minecraft:crimson_roots"
        ],
        "kind": "cross",
        "sound": "grass",
        "walkable": true,
        "nether": true,
        "worldgenWeight": 0
    },
    {
        "id": "nether_sprouts",
        "title": "Nether Sprouts",
        "vanilla": [
            "minecraft:nether_sprouts"
        ],
        "kind": "cross",
        "sound": "grass",
        "walkable": true,
        "nether": true,
        "worldgenWeight": 0
    },
    {
        "id": "warped_fungus",
        "title": "Warped Fungus",
        "vanilla": [
            "minecraft:warped_fungus"
        ],
        "kind": "cross",
        "sound": "grass",
        "walkable": true,
        "nether": true,
        "worldgenWeight": 0
    },
    {
        "id": "crimson_fungus",
        "title": "Crimson Fungus",
        "vanilla": [
            "minecraft:crimson_fungus"
        ],
        "kind": "cross",
        "sound": "grass",
        "walkable": true,
        "nether": true,
        "worldgenWeight": 0
    },
    {
        "id": "twisting_vines",
        "title": "Twisting Vines",
        "vanilla": [
            "minecraft:twisting_vines"
        ],
        "kind": "cross",
        "sound": "grass",
        "walkable": true,
        "nether": true,
        "worldgenWeight": 0
    },
    {
        "id": "weeping_vines",
        "title": "Weeping Vines",
        "vanilla": [
            "minecraft:weeping_vines"
        ],
        "kind": "cross",
        "sound": "grass",
        "walkable": true,
        "nether": true,
        "worldgenWeight": 0
    }
];

export const ALL_INFECTED_FOLIAGE_IDS = [];
export const ALL_INFECTED_FOLIAGE_WALKABLE_IDS = [];
export const DOUBLE_INFECTED_FOLIAGE_IDS = [];
export const CONVERTIBLE_FOLIAGE = new Set();

const vanillaToInfected = new Map();
const infectedToVanilla = new Map();
const infectedSet = new Set();

for (const spec of FOLIAGE_SPECIES) {
    const id = `mb:infected_${spec.id}`;
    ALL_INFECTED_FOLIAGE_IDS.push(id);
    infectedSet.add(id);
    infectedToVanilla.set(id, spec.vanilla[0]);
    if (spec.walkable) ALL_INFECTED_FOLIAGE_WALKABLE_IDS.push(id);
    if (spec.tall) DOUBLE_INFECTED_FOLIAGE_IDS.push(id);
    for (const v of spec.vanilla) {
        vanillaToInfected.set(v, id);
        CONVERTIBLE_FOLIAGE.add(v);
    }
    for (const v of spec.aliases || []) {
        vanillaToInfected.set(v, id);
        CONVERTIBLE_FOLIAGE.add(v);
    }
}

export function isInfectedFoliageId(typeId) {
    return infectedSet.has(typeId);
}

export function isConvertibleVanillaFoliage(typeId) {
    return CONVERTIBLE_FOLIAGE.has(typeId);
}

export function infectedFoliageIdForVanilla(typeId) {
    return vanillaToInfected.get(typeId);
}

export function vanillaFoliageIdForInfected(typeId) {
    return infectedToVanilla.get(typeId);
}

export function isInfectedFoliageWalkable(typeId) {
    return ALL_INFECTED_FOLIAGE_WALKABLE_IDS.includes(typeId);
}
