/**
 * Infected leaf + wood identifiers. Generated by tools/generateInfectedVegetationPack.js.
 * Do not edit by hand — change the generator and re-run it.
 */

export const LEAF_DUST_MAX = 3;

export const LEAF_SPECIES = [
    {
        "id": "oak",
        "title": "Oak",
        "vanilla": [
            "minecraft:oak_leaves",
            "minecraft:leaves"
        ],
        "sapling": "minecraft:oak_sapling",
        "apple": true,
        "needsBiomeConvert": false
    },
    {
        "id": "birch",
        "title": "Birch",
        "vanilla": [
            "minecraft:birch_leaves"
        ],
        "sapling": "minecraft:birch_sapling",
        "apple": false,
        "needsBiomeConvert": true
    },
    {
        "id": "spruce",
        "title": "Spruce",
        "vanilla": [
            "minecraft:spruce_leaves"
        ],
        "sapling": "minecraft:spruce_sapling",
        "apple": false,
        "needsBiomeConvert": true
    },
    {
        "id": "jungle",
        "title": "Jungle",
        "vanilla": [
            "minecraft:jungle_leaves"
        ],
        "sapling": "minecraft:jungle_sapling",
        "apple": false,
        "needsBiomeConvert": false
    },
    {
        "id": "acacia",
        "title": "Acacia",
        "vanilla": [
            "minecraft:acacia_leaves"
        ],
        "sapling": "minecraft:acacia_sapling",
        "apple": false,
        "needsBiomeConvert": false
    },
    {
        "id": "dark_oak",
        "title": "Dark Oak",
        "vanilla": [
            "minecraft:dark_oak_leaves",
            "minecraft:leaves2"
        ],
        "sapling": "minecraft:dark_oak_sapling",
        "apple": true,
        "needsBiomeConvert": false
    },
    {
        "id": "mangrove",
        "title": "Mangrove",
        "vanilla": [
            "minecraft:mangrove_leaves"
        ],
        "sapling": "minecraft:mangrove_propagule",
        "apple": false,
        "needsBiomeConvert": false
    },
    {
        "id": "cherry",
        "title": "Cherry",
        "vanilla": [
            "minecraft:cherry_leaves"
        ],
        "sapling": "minecraft:cherry_sapling",
        "apple": false,
        "needsBiomeConvert": true
    },
    {
        "id": "azalea",
        "title": "Azalea",
        "vanilla": [
            "minecraft:azalea_leaves"
        ],
        "sapling": "minecraft:azalea",
        "apple": false,
        "needsBiomeConvert": true
    },
    {
        "id": "flowering_azalea",
        "title": "Flowering Azalea",
        "vanilla": [
            "minecraft:azalea_leaves_flowered"
        ],
        "sapling": "minecraft:flowering_azalea",
        "apple": false,
        "needsBiomeConvert": true
    },
    {
        "id": "pale_oak",
        "title": "Pale Oak",
        "vanilla": [
            "minecraft:pale_oak_leaves"
        ],
        "sapling": "minecraft:pale_oak_sapling",
        "apple": false,
        "needsBiomeConvert": true
    },
    {
        "id": "red_poplar",
        "title": "Red Poplar",
        "vanilla": [
            "minecraft:red_poplar_leaves"
        ],
        "sapling": "minecraft:poplar_sapling",
        "apple": false,
        "needsBiomeConvert": true
    },
    {
        "id": "orange_poplar",
        "title": "Orange Poplar",
        "vanilla": [
            "minecraft:orange_poplar_leaves"
        ],
        "sapling": "minecraft:poplar_sapling",
        "apple": false,
        "needsBiomeConvert": true
    },
    {
        "id": "yellow_poplar",
        "title": "Yellow Poplar",
        "vanilla": [
            "minecraft:yellow_poplar_leaves"
        ],
        "sapling": "minecraft:poplar_sapling",
        "apple": false,
        "needsBiomeConvert": true
    }
];

export const WOOD_SPECIES = [
    {
        "id": "oak",
        "title": "Oak",
        "kinds": [
            {
                "id": "log",
                "title": "Log",
                "vanilla": "minecraft:oak_log",
                "infected": "mb:infected_oak_log"
            },
            {
                "id": "wood",
                "title": "Wood",
                "vanilla": "minecraft:oak_wood",
                "infected": "mb:infected_oak_wood"
            },
            {
                "id": "stripped_log",
                "title": "Stripped Log",
                "vanilla": "minecraft:stripped_oak_log",
                "infected": "mb:infected_stripped_oak_log"
            },
            {
                "id": "stripped_wood",
                "title": "Stripped Wood",
                "vanilla": "minecraft:stripped_oak_wood",
                "infected": "mb:infected_stripped_oak_wood"
            }
        ]
    },
    {
        "id": "birch",
        "title": "Birch",
        "kinds": [
            {
                "id": "log",
                "title": "Log",
                "vanilla": "minecraft:birch_log",
                "infected": "mb:infected_birch_log"
            },
            {
                "id": "wood",
                "title": "Wood",
                "vanilla": "minecraft:birch_wood",
                "infected": "mb:infected_birch_wood"
            },
            {
                "id": "stripped_log",
                "title": "Stripped Log",
                "vanilla": "minecraft:stripped_birch_log",
                "infected": "mb:infected_stripped_birch_log"
            },
            {
                "id": "stripped_wood",
                "title": "Stripped Wood",
                "vanilla": "minecraft:stripped_birch_wood",
                "infected": "mb:infected_stripped_birch_wood"
            }
        ]
    },
    {
        "id": "spruce",
        "title": "Spruce",
        "kinds": [
            {
                "id": "log",
                "title": "Log",
                "vanilla": "minecraft:spruce_log",
                "infected": "mb:infected_spruce_log"
            },
            {
                "id": "wood",
                "title": "Wood",
                "vanilla": "minecraft:spruce_wood",
                "infected": "mb:infected_spruce_wood"
            },
            {
                "id": "stripped_log",
                "title": "Stripped Log",
                "vanilla": "minecraft:stripped_spruce_log",
                "infected": "mb:infected_stripped_spruce_log"
            },
            {
                "id": "stripped_wood",
                "title": "Stripped Wood",
                "vanilla": "minecraft:stripped_spruce_wood",
                "infected": "mb:infected_stripped_spruce_wood"
            }
        ]
    },
    {
        "id": "jungle",
        "title": "Jungle",
        "kinds": [
            {
                "id": "log",
                "title": "Log",
                "vanilla": "minecraft:jungle_log",
                "infected": "mb:infected_jungle_log"
            },
            {
                "id": "wood",
                "title": "Wood",
                "vanilla": "minecraft:jungle_wood",
                "infected": "mb:infected_jungle_wood"
            },
            {
                "id": "stripped_log",
                "title": "Stripped Log",
                "vanilla": "minecraft:stripped_jungle_log",
                "infected": "mb:infected_stripped_jungle_log"
            },
            {
                "id": "stripped_wood",
                "title": "Stripped Wood",
                "vanilla": "minecraft:stripped_jungle_wood",
                "infected": "mb:infected_stripped_jungle_wood"
            }
        ]
    },
    {
        "id": "acacia",
        "title": "Acacia",
        "kinds": [
            {
                "id": "log",
                "title": "Log",
                "vanilla": "minecraft:acacia_log",
                "infected": "mb:infected_acacia_log"
            },
            {
                "id": "wood",
                "title": "Wood",
                "vanilla": "minecraft:acacia_wood",
                "infected": "mb:infected_acacia_wood"
            },
            {
                "id": "stripped_log",
                "title": "Stripped Log",
                "vanilla": "minecraft:stripped_acacia_log",
                "infected": "mb:infected_stripped_acacia_log"
            },
            {
                "id": "stripped_wood",
                "title": "Stripped Wood",
                "vanilla": "minecraft:stripped_acacia_wood",
                "infected": "mb:infected_stripped_acacia_wood"
            }
        ]
    },
    {
        "id": "dark_oak",
        "title": "Dark Oak",
        "kinds": [
            {
                "id": "log",
                "title": "Log",
                "vanilla": "minecraft:dark_oak_log",
                "infected": "mb:infected_dark_oak_log"
            },
            {
                "id": "wood",
                "title": "Wood",
                "vanilla": "minecraft:dark_oak_wood",
                "infected": "mb:infected_dark_oak_wood"
            },
            {
                "id": "stripped_log",
                "title": "Stripped Log",
                "vanilla": "minecraft:stripped_dark_oak_log",
                "infected": "mb:infected_stripped_dark_oak_log"
            },
            {
                "id": "stripped_wood",
                "title": "Stripped Wood",
                "vanilla": "minecraft:stripped_dark_oak_wood",
                "infected": "mb:infected_stripped_dark_oak_wood"
            }
        ]
    },
    {
        "id": "mangrove",
        "title": "Mangrove",
        "kinds": [
            {
                "id": "log",
                "title": "Log",
                "vanilla": "minecraft:mangrove_log",
                "infected": "mb:infected_mangrove_log"
            },
            {
                "id": "wood",
                "title": "Wood",
                "vanilla": "minecraft:mangrove_wood",
                "infected": "mb:infected_mangrove_wood"
            },
            {
                "id": "stripped_log",
                "title": "Stripped Log",
                "vanilla": "minecraft:stripped_mangrove_log",
                "infected": "mb:infected_stripped_mangrove_log"
            },
            {
                "id": "stripped_wood",
                "title": "Stripped Wood",
                "vanilla": "minecraft:stripped_mangrove_wood",
                "infected": "mb:infected_stripped_mangrove_wood"
            }
        ]
    },
    {
        "id": "cherry",
        "title": "Cherry",
        "kinds": [
            {
                "id": "log",
                "title": "Log",
                "vanilla": "minecraft:cherry_log",
                "infected": "mb:infected_cherry_log"
            },
            {
                "id": "wood",
                "title": "Wood",
                "vanilla": "minecraft:cherry_wood",
                "infected": "mb:infected_cherry_wood"
            },
            {
                "id": "stripped_log",
                "title": "Stripped Log",
                "vanilla": "minecraft:stripped_cherry_log",
                "infected": "mb:infected_stripped_cherry_log"
            },
            {
                "id": "stripped_wood",
                "title": "Stripped Wood",
                "vanilla": "minecraft:stripped_cherry_wood",
                "infected": "mb:infected_stripped_cherry_wood"
            }
        ]
    },
    {
        "id": "pale_oak",
        "title": "Pale Oak",
        "kinds": [
            {
                "id": "log",
                "title": "Log",
                "vanilla": "minecraft:pale_oak_log",
                "infected": "mb:infected_pale_oak_log"
            },
            {
                "id": "wood",
                "title": "Wood",
                "vanilla": "minecraft:pale_oak_wood",
                "infected": "mb:infected_pale_oak_wood"
            },
            {
                "id": "stripped_log",
                "title": "Stripped Log",
                "vanilla": "minecraft:stripped_pale_oak_log",
                "infected": "mb:infected_stripped_pale_oak_log"
            },
            {
                "id": "stripped_wood",
                "title": "Stripped Wood",
                "vanilla": "minecraft:stripped_pale_oak_wood",
                "infected": "mb:infected_stripped_pale_oak_wood"
            }
        ]
    },
    {
        "id": "poplar",
        "title": "Poplar",
        "kinds": [
            {
                "id": "log",
                "title": "Log",
                "vanilla": "minecraft:poplar_log",
                "infected": "mb:infected_poplar_log"
            },
            {
                "id": "wood",
                "title": "Wood",
                "vanilla": "minecraft:poplar_wood",
                "infected": "mb:infected_poplar_wood"
            },
            {
                "id": "stripped_log",
                "title": "Stripped Log",
                "vanilla": "minecraft:stripped_poplar_log",
                "infected": "mb:infected_stripped_poplar_log"
            },
            {
                "id": "stripped_wood",
                "title": "Stripped Wood",
                "vanilla": "minecraft:stripped_poplar_wood",
                "infected": "mb:infected_stripped_poplar_wood"
            }
        ]
    },
    {
        "id": "crimson",
        "title": "Crimson",
        "kinds": [
            {
                "id": "log",
                "title": "Stem",
                "vanilla": "minecraft:crimson_stem",
                "infected": "mb:infected_crimson_log"
            },
            {
                "id": "wood",
                "title": "Hyphae",
                "vanilla": "minecraft:crimson_hyphae",
                "infected": "mb:infected_crimson_wood"
            },
            {
                "id": "stripped_log",
                "title": "Stripped Stem",
                "vanilla": "minecraft:stripped_crimson_stem",
                "infected": "mb:infected_stripped_crimson_log"
            },
            {
                "id": "stripped_wood",
                "title": "Stripped Hyphae",
                "vanilla": "minecraft:stripped_crimson_hyphae",
                "infected": "mb:infected_stripped_crimson_wood"
            }
        ]
    },
    {
        "id": "warped",
        "title": "Warped",
        "kinds": [
            {
                "id": "log",
                "title": "Stem",
                "vanilla": "minecraft:warped_stem",
                "infected": "mb:infected_warped_log"
            },
            {
                "id": "wood",
                "title": "Hyphae",
                "vanilla": "minecraft:warped_hyphae",
                "infected": "mb:infected_warped_wood"
            },
            {
                "id": "stripped_log",
                "title": "Stripped Stem",
                "vanilla": "minecraft:stripped_warped_stem",
                "infected": "mb:infected_stripped_warped_log"
            },
            {
                "id": "stripped_wood",
                "title": "Stripped Hyphae",
                "vanilla": "minecraft:stripped_warped_hyphae",
                "infected": "mb:infected_stripped_warped_wood"
            }
        ]
    },
    {
        "id": "nether_wart",
        "title": "Nether Wart",
        "kinds": [
            {
                "id": "block",
                "title": "Block",
                "vanilla": "minecraft:nether_wart_block",
                "infected": "mb:infected_nether_wart_block"
            }
        ]
    },
    {
        "id": "warped_wart",
        "title": "Warped Wart",
        "kinds": [
            {
                "id": "block",
                "title": "Block",
                "vanilla": "minecraft:warped_wart_block",
                "infected": "mb:infected_warped_wart_block"
            }
        ]
    }
];

export function infectedLeafStageId(speciesId, stage) {
    const d = Math.max(0, Math.min(LEAF_DUST_MAX, stage | 0));
    return d === 0 ? `mb:infected_${speciesId}_leaves` : `mb:infected_${speciesId}_leaves_${d}`;
}

export const INFECTED_OAK_LEAF_STAGE_IDS = [0, 1, 2, 3].map((d) => infectedLeafStageId("oak", d));
export const INFECTED_OAK_LEAVES_ID = INFECTED_OAK_LEAF_STAGE_IDS[0];
export const INFECTED_BIRCH_LEAVES_ID = infectedLeafStageId("birch", 0);

const vanillaToSpecies = new Map();
const infectedToMeta = new Map();
export const ALL_INFECTED_LEAF_IDS = [];
export const CONVERTIBLE_LEAVES = new Set();
export const BIOME_CONVERT_VANILLA = new Set();

for (const spec of LEAF_SPECIES) {
    const stages = [0, 1, 2, 3].map((d) => infectedLeafStageId(spec.id, d));
    spec.stages = stages;
    for (const v of spec.vanilla) {
        vanillaToSpecies.set(v, spec);
        CONVERTIBLE_LEAVES.add(v);
        if (spec.needsBiomeConvert) BIOME_CONVERT_VANILLA.add(v);
    }
    stages.forEach((id, stage) => {
        ALL_INFECTED_LEAF_IDS.push(id);
        infectedToMeta.set(id, { spec, stage });
    });
}

const woodVanillaToInfected = new Map();
export const ALL_INFECTED_WOOD_IDS = [];
export const CONVERTIBLE_WOOD = new Set();

for (const spec of WOOD_SPECIES) {
    for (const kind of spec.kinds) {
        woodVanillaToInfected.set(kind.vanilla, kind.infected);
        CONVERTIBLE_WOOD.add(kind.vanilla);
        ALL_INFECTED_WOOD_IDS.push(kind.infected);
    }
}

export function isInfectedLeafId(typeId) {
    return infectedToMeta.has(typeId);
}

export function isConvertibleVanillaLeaf(typeId) {
    return CONVERTIBLE_LEAVES.has(typeId);
}

export function leafMetaFromInfectedId(typeId) {
    return infectedToMeta.get(typeId);
}

export function vanillaLeafIdForInfected(typeId) {
    const meta = infectedToMeta.get(typeId);
    if (!meta?.spec?.vanilla?.length) return undefined;
    return meta.spec.vanilla[0];
}

export function speciesFromVanillaLeaf(typeId) {
    return vanillaToSpecies.get(typeId);
}

export function infectedLeafIdForVanilla(typeId, stage = 0) {
    const spec = vanillaToSpecies.get(typeId);
    if (!spec) return undefined;
    return infectedLeafStageId(spec.id, stage);
}

export function snowStageIdForInfected(typeId) {
    const meta = infectedToMeta.get(typeId);
    if (!meta) return undefined;
    return infectedLeafStageId(meta.spec.id, LEAF_DUST_MAX);
}

export function snowStageIdForVanillaLeaf(typeId) {
    const spec = vanillaToSpecies.get(typeId);
    if (!spec) return undefined;
    return infectedLeafStageId(spec.id, LEAF_DUST_MAX);
}

const infectedWoodSet = new Set(ALL_INFECTED_WOOD_IDS);

export function isInfectedWoodId(typeId) {
    return infectedWoodSet.has(typeId);
}

export function isConvertibleVanillaWood(typeId) {
    return CONVERTIBLE_WOOD.has(typeId);
}

export function infectedWoodIdForVanilla(typeId) {
    return woodVanillaToInfected.get(typeId);
}

export function vanillaWoodIdForInfected(typeId) {
    for (const spec of WOOD_SPECIES) {
        for (const kind of spec.kinds) {
            if (kind.infected === typeId) return kind.vanilla;
        }
    }
    return undefined;
}
